### ISSUE TITLE
Question about visualization

### ISSUE THREAD

**Issue by jiahaoli95** [NVlabs/GroupViT#24]
Hi, thanks for the amazing work! I have two questions about the paper. In my understanding, the resolution of the mask is restricted by the number of patches. In the paper, it says that during testing the shorter side is resized to 448. With a patch size 16, the mask resolution is 28 for the shorter side.

1. Many of the visualization results in the paper show very smooth masks. Some have very high frequency noise (very small isolated dots in a mask). I do some rough calculation, it does not seem to have a resolution of only 28. Do you use an even larger image size for the visualization results? Or I am missing something?
2. If I understand correctly, you are using 224x224 images for training, but use 448 directly for testing without any further modification to the model. There should be a data distribution mismatch between training and testing, right? Do you have any sense about how this affects the results? For example, maybe testing on 448x448 imagenet images to see how the accuracy changes?

Thank you!
Jiahao

**Comment by xvjiarui** [comment]
Hi @jiahaoli95 
1. The attention map is bilinearly resized. You may refer to the demo code for details https://github.com/NVlabs/GroupViT/blob/main/demo/demo_seg.py . We use soft attention map during inference. So we could get better details. 
2. We didn't test 448 resolution on ImageNet. The zero-shot classification accuracy may drop.  We use 448 resolution during zero-shot semantic segmentation because we need higher resolution for the segmentation prediction.

**Comment by jiahaoli95** [comment]
Make sense. Thanks!
